---
- name: Configuro servidor base de datos en ubuntu #Asignacion de nombre a play
  hosts: database #Hosts a quien va dedicado
  become: true #Estado de Become
  user: sysadmin #Usuario que utliza

  tasks:

  - name: UFW instalado #Nombre de la tarea
    ansible.builtin.apt: #Modulo que utilizaremos
      name: ufw #Nombre que se le asignara al modulo
      state: present #Estado del modulo

##############################################################################################################################################
  - name: Permitir puerto 22
    command: ufw allow 22/tcp

  - name: Permitir todo el tráfico saliente
    command: ufw default allow outgoing

  - name: Denegar todo el tráfico entrante
    command: ufw default deny incoming
##############################################################################################################################################

  - name: servicio UFW levantado y activo #Nombre de la tarea
    ansible.builtin.systemd_service: #Modulo que utilizaremos
      name: ufw
      state: started
      enabled: true

## Instalación de base de datos
  - name: MariaDB instalado #Nombre de la tarea
    ansible.builtin.apt: #Modulo que utilizaremos
      name: mariadb-server #Nombre que se le asignara al modulo
      state: present #Estado del modulo
      update-cache: true

  - name: Cambiar la configuracion para escuchar en todas las interfaces #Nombre de la tarea
    ansible.builtin.lineinfile: #Modulo que utilizaremos
      path: /etc/mysql/mariadb.conf.d/50-server.cnf #Direccion donde se cambia configuraicon
      regexp: '^bind-address' #Linea que cambiara
      line: 'bind-address         = 0.0.0.0' #Linea que cambiara
    notify: Restart mariadb #Notifica a la tarea Restar mariadb para que se ejecute

  - name: Servidor Mariadb levantado #Nombre de la tarea
    ansible.builtin.systemd_service:  #Modulo que utilizaremos
      name: mariadb #Nombre del modulo
      state: started #Estado del modulo
      enabled: true #Estado del modulo

###############################################################################################################################################
  - name: Permitir conexiones entrantes a MariaDB en el puerto 3306
    command: ufw allow 3306/tcp
###############################################################################################################################################

##  Configuracion de la base de datos

###############################################################################################################################################
  - name: Crear la base de datos todo
    command: mysql -h {{ hostvars[inventory_hostname].ansible_host }} -u root -pdbadmin -e "CREATE DATABASE IF NOT EXISTS todo;"

  - name: Importar el archivo SQL
    command: mysql -h {{ hostvars[inventory_hostname].ansible_host }} -u root -pdbadmin todo < ./files/todo.sql
###############################################################################################################################################

  handlers:

  - name: Restart mariadb 
    ansible.builtin.systemd_service: 
      name: mariadb
      state: restarted