---
#Acciones que se ejecutan mediante el presente playbook
#UFW instalado
#Permite puerto 22 en ufw
#Define politicas de trafico saliente
#Define politicas de trafica entrante
#Servicio ufw levantado
#Servidor MariaDB instalado
#Cambiar la configuracion para escuchar en todas las interfaces
#Verifica servidor Mariadb levantado
#Habilitamos en ufw la conexión a mariadb
#Creo la base de datos todo
#Importar el archivo SQL en la base de datos "todo"
#Reinicia servidor MariaDB
- name: Configuro servidor base de datos en ubuntu #Asignacion de nombre a play
  hosts: database #Hosts a quien va dedicado
  become: true #Estado de Become
  user: sysadmin #Usuario que utliza
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: UFW instalado #Nombre de la tarea
    ansible.builtin.apt: #Modulo que utilizaremos
      name: ufw #Nombre que se le asignara al modulo
      state: present #Estado del modulo

##############################################################################################################################################
  - name: Permitir puerto 22 en ufw
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: Defino politicas de tráfico saliente
    community.general.ufw:
      policy: allow
      direction: outgoing
      state: enabled

  - name: Defino politicas de tráfico entrante
    community.general.ufw:
      policy: deny
      direction: incoming
      state: enabled
##############################################################################################################################################

  - name: servicio UFW levantado y activo #Nombre de la tarea
    ansible.builtin.systemd_service: #Modulo que utilizaremos
      name: ufw
      state: started
      enabled: true

## Instalación de base de datos
  - name: MariaDB instalado #Nombre de la tarea
    ansible.builtin.apt: #Modulo que utilizaremos
      name: mariadb-server #Nombre que se le asignara al modulo
      state: present #Estado del modulo
      update-cache: true

  - name: Cambiar la configuracion para escuchar en todas las interfaces #Nombre de la tarea
    ansible.builtin.lineinfile: #Modulo que utilizaremos
      path: /etc/mysql/mariadb.conf.d/50-server.cnf #Direccion donde se cambia configuraicon
      regexp: '^bind-address' #Linea que cambiara
      line: 'bind-address         = 0.0.0.0' #Linea que cambiara
    notify: Restart mariadb #Notifica a la tarea Restar mariadb para que se ejecute

  - name: Servidor Mariadb levantado #Nombre de la tarea
    ansible.builtin.systemd_service:  #Modulo que utilizaremos
      name: mariadb #Nombre del modulo
      state: started #Estado del modulo
      enabled: true #Estado del modulo

  - name: Habilitamos en ufw la conexión a mariadb
    community.general.ufw:
      rule: allow
      port: '3306'
      protocol: tcp
      direction: in

##  Configuracion de la base de datos

  - name: Creo la base de datos todo
    community.mysql.mysql_db:
      check_implicit_admin: true
      name: todo
      state: present
      login_host: "{{ hostvars[inventory_hostname].ansible_host }}"
      login_user: root
      login_password: tlxadmin
      target: ./files/todo.sql
    delegate_to: localhost
    connection: local

  - name: Importar el archivo SQL en la base de datos "todo"
    community.mysql.mysql_db:
      name: todo
      state: import
      target: ./files/todo.sql
      login_user: root
      login_password: tlxadmin
      login_host: 192.168.56.105
    delegate_to: localhost
    connection: local

  handlers:

  - name: Restart mariadb 
    ansible.builtin.systemd_service: 
      name: mariadb
      state: restarted