---
- name: Instalar Podman en ubuntu
  hosts: centos
  become: yes
  tasks:
    - name: Instalar dependencias
      apt:
        name:
          - software-properties-common
          - gnupg2
          - lsb-release
        state: present
        update_cache: yes

    - name: Agregar repositorio de Podman
      shell: |
        source /etc/os-release
        echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$ID_$VERSION_ID/ /" | tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$ID_$VERSION_ID/Release.key | apt-key add -

    - name: Actualizar caché de paquetes
      apt:
        update_cache: yes

    - name: Instalar Podman
      apt:
        name: podman
        state: present