---
- name: Desplegar aplicación web en Tomcat
  hosts: centos
  become: true
  user: sysadmin

  tasks:
  - name: Instalar OpenJDK 11
    ansible.builtin.dnf:
      name: java-11-openjdk
      state: present

  - name: Limpiar la caché de dnf
    ansible.builtin.command:
      cmd: dnf clean all

  - name: Crear directorio para Tomcat
    ansible.builtin.file:
      path: /opt/tomcat
      state: directory
  
  - name: Descargar Tomcat
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.100/bin/apache-tomcat-8.5.100.tar.gz
      dest: /tmp/apache-tomcat-8.5.100.tar.gz

  - name: Extraer Tomcat
    ansible.builtin.unarchive:
      src: /tmp/apache-tomcat-8.5.100.tar.gz
      dest: /opt/tomcat
      remote_src: true

  - name: Mover archivos de Tomcat a /opt/tomcat
    ansible.builtin.command:
      cmd: mv /opt/tomcat/apache-tomcat-8.5.100/* /opt/tomcat/.

  - name: Copiar todo.war a Tomcat
    ansible.builtin.copy:
      src: ./files/todo.war
      dest: /opt/tomcat/webapps/

#######################################################################################################################################
  - name: Permitir puerto 8080
    command: ufw allow 8080/tcp
#######################################################################################################################################

  - name: Verificar que Tomcat se está ejecutando
    ansible.builtin.command:
      cmd: /opt/tomcat/bin/catalina.sh run
    async: 45
    poll: 0

  handlers:

  - name: Reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded