---
- name: Desplegar aplicación web en Tomcat
  hosts: centos
  become: true
  user: sysadmin

  tasks:
  - name: Instalar OpenJDK 11
    ansible.builtin.dnf:
      name: java-11-openjdk
      state: present

  - name: Limpiar la caché de dnf
    ansible.builtin.command:
      cmd: dnf clean all

  - name: Crear directorio para Tomcat
    ansible.builtin.file:
      path: /opt/tomcat
      state: directory
  
  - name: Descargar Tomcat
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.91/bin/apache-tomcat-9.0.91.tar.gz
      dest: /tmp/apache-tomcat-9.0.91.tar.gz
      mode: '0644'

  - name: Extraer Tomcat
    ansible.builtin.unarchive:
      src: /tmp/apache-tomcat-9.0.91.tar.gz
      dest: /opt/tomcat
      remote_src: yes

  - name: Copiar todo.war a Tomcat
    ansible.builtin.copy:
      src: ./files/todo.war
      dest: /opt/tomcat/webapps/

  - name: Habilitar puertos en el Firewall
    ansible.posix.firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled

  - name: Crear el archivo de servicio systemd para Tomcat
    ansible.builtin.copy:
      dest: /etc/systemd/system/tomcat.service
      content: |
       [Unit]
       Description=Apache Tomcat
       After=network.target

       [Service]
       Type=forking
       User=root
       Group=root
       Environment=JAVA_HOME=/usr/lib/jvm/jre
       Environment=CATALINA_PID=opt/tomcat/temp/tomcat.pid
       Environment=CATALINA_HOME=opt/tomcat
       Environment=CATALINA_BASE=opt/tomcat
       Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
       Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'
       ExecStart=opt/tomcat/apache-tomcat-9.0.91/bin/startup.sh
       ExecStop=opt/tomcat/apache-tomcat-9.0.91/bin/shutdown.sh
       ExecReload=/apache-tomcat-9.0.91/kill -s HUP $MAINPID
       SuccessExitStatus=143
       Restart=always

       [Install]
       WantedBy=multi-user.target

  - name: Recargar daemon de systemd
    ansible.builtin.command: systemctl daemon-reload

  - name: Iniciar Tomcat
    ansible.builtin.command:
      cmd: /opt/tomcat/apache-tomcat-9.0.91/bin/startup.sh
      chdir: /opt/tomcat

  handlers:

  - name: Reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded