---
#Acciones que se ejecutan mediante el presente playbook
#Se instala OpenJKD 11
#Limpia la cache de dnf
#Crea directorio para Tomcat
#Descarga Tomcat
#Extrae Tomcat
#Copia la app a Tomcat
#Habilita puertos en el firewalld
#Crea el archivo de servicio systemd para Tomcat
#Recargar daemon de systemd
#Inicia Tomcat
#Recarga Firewalld
- name: Desplegar aplicación web en Apache Tomcat
  hosts: centos
  become: true
  user: sysadmin

  tasks:
  - name: Instalar OpenJDK 11
    ansible.builtin.dnf:
      name: java-11-openjdk
      state: present

  - name: Limpiar la caché de dnf
    ansible.builtin.command:
      cmd: dnf clean all

  - name: Crear directorio para Tomcat
    ansible.builtin.file:
      path: /opt/tomcat
      state: directory
      mode: '0755'
  
  - name: Crear el grupo tomcat
    group:
      name: tomcat
      state: present

  - name: Crear usuario tomcat
    user:
      name: tomcat
      group: tomcat
      create_home: no
      shell: /sbin/nologin
      state: present

  - name: Instalar apache
    ansible.builtin.dnf:
      name: httpd
      state: present

  - name: Descargar Tomcat
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.26/bin/apache-tomcat-10.1.26.tar.gz
      dest: /tmp/apache-tomcat-10.1.26.tar.gz

  - name: Extraer Tomcat
    ansible.builtin.unarchive:
      src: /tmp/apache-tomcat-10.1.26.tar.gz
      dest: /opt/tomcat
      remote_src: yes

  - name: Copiar todo.war a Tomcat
    ansible.builtin.copy:
      src: ./files/todo.war
      dest: /opt/tomcat/apache-tomcat-10.1.26/webapps/

  - name: Habilitar puertos en el Firewall
    ansible.posix.firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled

  - name: Crear el archivo de servicio systemd para Tomcat
    ansible.builtin.copy:
      dest: /etc/systemd/system/tomcat.service
      content: |
        [Unit]
        Description=Apache Tomcat Web Application Container
        After=network.target

        [Service]
        Type=forking
        User=tomcat
        Group=tomcat
        Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk"
        Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
        ExecStart=/opt/tomcat/apache-tomcat-10.1.26/bin/startup.sh
        ExecStop=/opt/tomcat/apache-tomcat-10.1.26/bin/shutdown.sh
        SuccessExitStatus=143
        Restart=on-failure

        [Install]
        WantedBy=multi-user.target

  - name: Asignar permisos correctos al directorio de Tomcat
    ansible.builtin.command:
      cmd: chown -R tomcat:tomcat /opt/tomcat

  - name: Recargar systemd
    systemd:
      daemon_reload: yes

  - name: Iniciar y habilitar apache
    systemd:
     name: httpd
     state: started
     enabled: yes
  
  - name: Iniciar y habilitar Tomcat
    systemd:
     name: tomcat
     enabled: yes
     state: started
  
  handlers:

  - name: Reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded